apiVersion: v1
kind: LimitRange
metadata:
  name: aislemarts-limits
  namespace: staging
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "250m"
      memory: "512Mi"
    max:
      cpu: "4"
      memory: "4Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
  - type: Pod
    max:
      cpu: "8"
      memory: "8Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: aislemarts-limits
  namespace: prod
spec:
  limits:
  - type: Container
    default:
      cpu: "2"
      memory: "2Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    max:
      cpu: "8"
      memory: "8Gi"
    min:
      cpu: "250m"
      memory: "256Mi"
  - type: Pod
    max:
      cpu: "16"
      memory: "16Gi"