apiVersion: v1
kind: ResourceQuota
metadata:
  name: aislemarts-quota
  namespace: staging
spec:
  hard:
    requests.cpu: "8"
    requests.memory: "16Gi"
    limits.cpu: "16"
    limits.memory: "32Gi"
    persistentvolumeclaims: "10"
    pods: "50"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: aislemarts-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "50"
    requests.memory: "100Gi"
    limits.cpu: "100"
    limits.memory: "200Gi"
    persistentvolumeclaims: "20"
    pods: "100"
    services: "20"
    secrets: "20"
    configmaps: "20"