# 🌍 AisleMarts WebSocket Real-time Services
# GKE Autopilot deployment for live features

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aislemarts-websocket
  namespace: default
  labels:
    app: aislemarts-websocket
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aislemarts-websocket
  template:
    metadata:
      labels:
        app: aislemarts-websocket
        version: v1
    spec:
      serviceAccountName: aislemarts-gke-sa
      containers:
      - name: websocket-server
        image: us-central1-docker.pkg.dev/PROJECT_ID/aislemarts-images/websocket:latest
        ports:
        - containerPort: 8080
          name: websocket
        env:
        - name: PROJECT_ID
          value: "PROJECT_ID"
        - name: ENVIRONMENT
          value: "prod"
        - name: REDIS_HOST
          value: "REDIS_HOST"
        - name: FIRESTORE_COLLECTION
          value: "realtime_sessions"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: aislemarts-websocket-service
  labels:
    app: aislemarts-websocket
spec:
  selector:
    app: aislemarts-websocket
  ports:
  - name: websocket
    port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aislemarts-websocket-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "aislemarts-global-ip"
    networking.gke.io/managed-certificates: "aislemarts-ssl-cert"
    kubernetes.io/ingress.class: "gce"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  rules:
  - host: ws.aislemarts.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aislemarts-websocket-service
            port:
              number: 80

---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: aislemarts-ssl-cert
spec:
  domains:
    - ws.aislemarts.com
    - api.aislemarts.com
    - aislemarts.com

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aislemarts-websocket-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aislemarts-websocket
  minReplicas: 3
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80