# AisleMarts Production Secrets Template
# Replace placeholder values with actual secrets

apiVersion: v1
kind: Secret
metadata:
  name: aislemarts-secrets
  namespace: aislemarts-prod
type: Opaque
stringData:
  mongo-url: "mongodb://username:password@mongodb-0.mongodb-service.aislemarts-prod.svc.cluster.local:27017,mongodb-1.mongodb-service.aislemarts-prod.svc.cluster.local:27017,mongodb-2.mongodb-service.aislemarts-prod.svc.cluster.local:27017/aislemarts?replicaSet=rs0"
  openai-api-key: "sk-proj-YOUR_OPENAI_API_KEY_HERE"
  stripe-secret-key: "sk_live_YOUR_STRIPE_SECRET_KEY_HERE"
  stripe-webhook-secret: "whsec_YOUR_STRIPE_WEBHOOK_SECRET_HERE"
  jwt-secret: "YOUR_JWT_SECRET_256_BITS_HERE"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: aislemarts-prod
type: Opaque
stringData:
  username: "aislemarts_admin"
  password: "YOUR_STRONG_MONGODB_PASSWORD_HERE"

---
# S3 backup credentials
apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: aislemarts-prod
type: Opaque
stringData:
  aws-access-key-id: "YOUR_AWS_ACCESS_KEY_ID"
  aws-secret-access-key: "YOUR_AWS_SECRET_ACCESS_KEY"
  aws-region: "us-east-1"
  s3-bucket: "aislemarts-production-backups"