openapi: 3.0.3
info:
  title: AisleMarts Multi-Vendor APIs
  version: 1.0.0
paths:
  /seller/products:
    get:
      summary: List seller products
      responses:
        '200':
          description: OK
    post:
      summary: Create product
      responses:
        '201':
          description: Created
  /seller/products/{id}:
    get:
      summary: Read product
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    put:
      summary: Update product
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: Updated }
    delete:
      summary: Delete product
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: Deleted }
  /seller/products/{id}/toggle:
    post:
      summary: Toggle product active/pause
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
  /seller/orders:
    get:
      summary: List seller orders
      responses:
        '200': { description: OK }
  /seller/orders/{id}:
    get:
      summary: Get order detail
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK }
    post:
      summary: Update order status
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [pending, paid, shipped, delivered, cancelled]
      responses:
        '200': { description: Updated }
  /seller/analytics/summary:
    get:
      summary: Seller KPIs for dashboard
      responses:
        '200': { description: OK }
  /seller/analytics/timeseries:
    get:
      summary: KPI timeseries for charts
      parameters:
        - in: query
          name: metric
          schema: { type: string, enum: [revenue, orders, views, ctr, ai_share] }
      responses:
        '200': { description: OK }
