name: Readiness Gate

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Run master validator (creates JSON report)
        env:
          BASE_URL: ${{ secrets.API_BASE_URL }}
          HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
          RUN_E2E: "0"
        run: |
          chmod +x aislemarts_one_click.sh || true
          if [ -x aislemarts_one_click.sh ]; then
            ./aislemarts_one_click.sh
          else
            echo "one_click not found; using final_validation.sh"
            chmod +x final_validation.sh
            ./final_validation.sh
          fi

      - name: Enforce 95%+
        run: |
          json=$(ls -1 reports/*/summary.json 2>/dev/null | tail -1 || true)
          if [ -z "$json" ]; then
            echo "No JSON summary found; failing for safety."
            exit 1
          fi
          score=$(jq -r '.score // 0' "$json")
          echo "Readiness score: $score%"
          [ "$score" -ge 95 ] || (echo "Readiness gate failed (<95%)" && exit 1)

      # Optional UI e2e (enable when simulators are available in CI)
      # - name: Detox iOS
      #   run: npm run e2e:build:ios && npm run e2e:test:ios
      # - name: Detox Android
      #   run: npm run e2e:build:android && npm run e2e:test:android